version: "3.3"
    
services:
  sql:
    image: mcr.microsoft.com/azure-sql-edge
    container_name: SQL 
    restart: unless-stopped
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'testPW12345678!'
    ports:
      - '30001:1433'
        
  mongo:
    image: mongo
    container_name: Mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin 
      MONGO_INITDB_ROOT_PASSWORD: testPW12345678!